version: '2'
services:
  namenode:
    build: ./hdfs/master
    image: khkwon/hadoop/hdfs/namenode
    links:
      - zookeeper
    ports:
      - 50070:50070
    environment:
      HADOOP_NAMENODE_URI: namenode
    container_name: namenode
    hostname: namenode

  datanode:
    build: ./hdfs/slave
    image: khkwon/hadoop/hdfs/datanode
    links:
      - zookeeper
    links:
      - namenode
    environment:
      HADOOP_NAMENODE_URI: namenode

    container_name: hbasemaster

  zookeeper:
    build: ./zookeeper
    image: khkwon/hadoop/zookeeper
    container_name: zk1
    command: '1'
