version: '2'
services:
  client:
    tty: true
    build: ./client
    image: khkwon/hadoop/client
    volumes:
      - ./client/data/hadoop:/tmp/hadoop
    command: bash
    container_name: hadoop_client

  namenode:
    build: ./hdfs/master
    image: khkwon/hadoop/hdfs/namenode
    ports:
      - 50070:50070
      - 9000:9000
      - 8030:8030
      - 8047:8047
      - 8141:8141
      - 8088:8088
      - 45454:45454
      - 16000:16000
      - 16010:16010
      - 4040:4040
    environment:
      HADOOP_NAMENODE_URI: namenode
    container_name: namenode
    hostname: namenode

  datanode1:
    build: ./hdfs/slave
    image: khkwon/hadoop/hdfs/datanode
    environment:
      HADOOP_NAMENODE_URI: namenode
    hostname: hadoop_datanode1_1.hadoop_default
    ports:
      - 16020:16020
      - 16030:16030

  datanode2:
    image: khkwon/hadoop/hdfs/datanode
    environment:
      HADOOP_NAMENODE_URI: namenode
    hostname: hadoop_datanode2_1.hadoop_default

  datanode3:
    image: khkwon/hadoop/hdfs/datanode
    environment:
      HADOOP_NAMENODE_URI: namenode
    hostname: hadoop_datanode3_1.hadoop_default

  zookeeper:
    image: zookeeper:3.4.9
    ports:
      - 2181:2181
    container_name: zk1
