version: '2'
services:
  client:
    tty: true
    build: ./client
    image: khkwon/hadoop/client
    links:
      - namenode
    volumes:
      - ./client/data/hadoop:/tmp/hadoop
    command: bash
    container_name: hadoop_client

  namenode:
    build: ./hdfs/master
    image: khkwon/hadoop/hdfs/namenode
    links:
      - zookeeper
    ports:
      - 50070:50070
      - 8030:8030
      - 8141:8141
      - 8088:8088
      - 45454:45454
    environment:
      HADOOP_NAMENODE_URI: namenode
    container_name: namenode
    hostname: namenode

  datanode:
    build: ./hdfs/slave
    image: khkwon/hadoop/hdfs/datanode
    links:
      - zookeeper
      - namenode
    environment:
      HADOOP_NAMENODE_URI: namenode

  zookeeper:
    build: ./zookeeper
    image: khkwon/hadoop/zookeeper
    container_name: zk1
    command: '1'
