#!/bin/sh

command="$@"

if [ $command = "start" ]; then
    echo "start hadoop"
    docker-compose up -d zookeeper namenode
    docker-compose scale datanode=3

elif [ $command = "stop" ]; then
    docker-compose kill
    docker-compose rm
fi
