#!/bin/sh

command="$@"

if [ $command = "start" ]; then
  echo "start hadoop"
  docker-compose up -d zookeeper namenode
  docker-compose scale datanode=4
elif [ $command = "stop" ]; then
  docker-compose kill
  echo "y\n" | docker-compose rm
elif [ $command = "client" ]; then
  docker-compose up -d client
  docker exec -it hadoop_client bash
fi
